IMGPATH=${1?no image path provided}
IMGTYPE=${2?no image type specified}
RUNTYPE=${3?no emulate type specified}
RUN_MEGS=${4?no emulate memory size specified}
echo "Generating bochsrc file ..." >&2
case $RUNTYPE in
	slow)	COMM_GDB=\#;
		COMM_TERM=\#;;
	fast)	COMM_GDB=\#;
		COMM_SLOW=\#;
		COMM_TERM=\#;;
	term)	COMM_GDB=\#;;
	*)	COMM_GDB=\#;;
esac
case $IMGTYPE in
	fda)	FDA_IMGPATH=$IMGPATH;
		COMM_HDA=\#;;
	hda)	FDA_IMGPATH=floppya.img;;
	*)	FDA_IMGPATH=$IMGPATH;
		COMM_HDA=\#;;
esac
cat << __EOF__
#############################################################
# Bochs configure file atomatic generated by bochsrc-gen.sh #
#############################################################
megs: $RUN_MEGS
#cpu: count=1, ips=6000000, reset_on_triple_fault=1, ignore_bad_msrs=1
${COMM_SLOW}clock: sync=slowdown, time0=local
romimage: file=\$BXSHARE/BIOS-bochs-latest #, address=0xf0000
vgaromimage: file=\$BXSHARE/VGABIOS-lgpl-latest
floppya: 1_44="$FDA_IMGPATH", status=inserted
floppyb: 1_44=floppyb.img, status=inserted
#ata0: enabled=1, ioaddr1=0x1f0, ioaddr2=0x3f0, irq=14
${COMM_HDA}ata0-master: type=disk, path="$IMGPATH", mode=flat
#ata0-master: type=disk, path="hda.img", mode=flat, cylinders=20, heads=16, spt=63
#ata0-master: type=disk, path="hda.img", mode=flat, cylinders=20, heads=16, spt=63
#ata0-master: type=disk, path="hd0.img", cylinders=20, heads=16, spt=63
boot: a
#config_interface: textconfig
#config_interface: wx
#display_library: x
${COMM_TERM}display_library: term
#display_library: win32 sdl wx carbon amigaos beos macintosh nogui rfb term svga
log: bochs.out
mouse: enabled=0
#keyboard_mapping: enabled=1, map=\$BXSHARE/keymaps/x11-pc-us.map
#keyboard_mapping: enabled=1, map=\$BXSHARE/keymaps/x11-pc-fr.map
#keyboard_mapping: enabled=1, map=\$BXSHARE/keymaps/x11-pc-de.map
#keyboard_mapping: enabled=1, map=\$BXSHARE/keymaps/x11-pc-es.map
${COMM_GDB}gdbstub: enabled=1, port=1234, text_base=0, data_base=0, bss_base=0
__EOF__
exit 0
